# Generated by Django 2.2.5 on 2020-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200825_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='house_rules',
        ),
        migrations.AddField(
            model_name='room',
            name='house_rules',
            field=models.ManyToManyField(to='rooms.HouseRule'),
        ),
    ]
