# Generated by Django 2.2.5 on 2020-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200825_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('confirmed', 'confirmed'), ('pending', 'pending')], default='pending', max_length=12),
        ),
    ]
