# Generated by Django 2.2.5 on 2020-08-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200825_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('pending', 'pending'), ('canceled', 'canceled')], default='pending', max_length=12),
        ),
    ]
