# Generated by Django 2.2.5 on 2020-08-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200829_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('confirmed', 'confirmed'), ('pending', 'pending')], default='pending', max_length=12),
        ),
    ]
