# Generated by Django 2.2.5 on 2020-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20200831_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=12),
        ),
    ]
