# Generated by Django 2.2.5 on 2020-09-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20200901_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('canceled', 'canceled'), ('pending', 'pending')], default='pending', max_length=12),
        ),
    ]
