# Generated by Django 2.2.5 on 2020-09-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20200905_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('confirmed', 'confirmed'), ('pending', 'pending')], default='pending', max_length=12),
        ),
    ]
