# Generated by Django 2.2.5 on 2020-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20200905_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('pending', 'pending'), ('canceled', 'canceled')], default='pending', max_length=12),
        ),
    ]
