# Generated by Django 2.2.5 on 2020-08-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='check',
            new_name='check_in',
        ),
    ]
